format = '''
$time $directory
$character
'''
# move the rest of the prompt to the right
#right_format = """$all"""
# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
success_symbol = '[|](bold red)[|](bold green)[|](bold blue)[|](bold purple)[|](bold yellow)'
error_symbol = '[|](bold red)[|](bold red)[|](bold red)[|](bold red)[|](bold red)'


[aws]
disabled = true

[time]
disabled = false
format = '[$time](white bold)'
# style = 'white bold'
time_format = '%H:%M'

[directory]
style = 'white bold'
